version: "3.8"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: signoz-clickhouse
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=signoz_traces
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
      - "8123:8123"

  zookeeper:
    image: zookeeper:3.7
    container_name: signoz-zookeeper
    ports:
      - "2181:2181"

  signoz-query-service:
    image: signoz/query-service:latest
    container_name: signoz-query-service
    restart: always
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      - SIGNOZ_TELEMETRYSTORE_PROVIDER=clickhouse
      - SIGNOZ_CLICKHOUSE_HOST=clickhouse
      - SIGNOZ_CLICKHOUSE_PORT=9000
      - SIGNOZ_DB_DSN=tcp://clickhouse:9000?username=default&database=signoz_traces
      - SIGNOZ_LOG_LEVEL=info

  signoz-frontend:
    image: signoz/frontend:latest
    container_name: signoz-frontend
    restart: always
    depends_on:
      - signoz-query-service
    environment:
      - PUBLIC_API_ENDPOINT=http://signoz-query-service:8080
    ports:
      - "3301:3301"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./signoz-otel-collector.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - signoz-query-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
